# Docker Compose file for running a Python 2.7 environment
# with androguard installed and a mapped volume for data persistence.

version: '3.8'

services:
  py27_android_guard:
    # This tells Docker Compose to build a custom image.
    # It will look for a file named 'Dockerfile' in the current directory.
    build: .

    # A friendly name for the container once it's running.
    container_name: py27_android_guard_container

    # This section maps a directory from your host machine to a directory
    # inside the container.
    volumes:
      # Format: [host_path]:[container_path]
      # This line maps the '/data/' directory on your host machine to the
      # '/app/data' directory inside the container.
      # Any files you place in /data/ on your computer will appear in /app/data
      # inside the container, and vice-versa.
      - /data:/app/data
      - ./MaMadroid:/app/code
    # Sets the default directory for commands run inside the container.
    working_dir: /app

    # This command keeps the container running in the background.
    # Without it, the container would start and immediately stop.
    # You can attach to the container to run your commands.
    command: tail -f /dev/null

