# Use the official Python 2.7 image as a base
FROM python:2.7-slim

# Set the working directory inside the container
WORKDIR /app


# Install the androguard package using pip
# This command is run when the Docker image is built.
RUN pip install androguard==3.3.5
RUN pip install python-igraph==0.8.0
# By default, when the container starts, it will be in the /app directory.


