nohup python -u mcndroid_cl_class_inc.py \
  --dataset_root ./mcndroid_malware_class_inc_dataset \
  --modalities data,gml,json,fusion \
  --strategies none,joint,ER \
  --num_seeds 1 \
  --epochs 100 \
  --batch_size 512 \
  --lr 0.001 \
  --replay_buffer_sizes 1000 \
  --replay_ratio 0.5 \
  --out_dir ./mcndroid_class_inc_output > cl_class_inc_out.log 2>&1 &
